export const level = {
    id: 11,
    definition: {
        TITLE: 'Bastion Relay',
        GRAVITY: 300,
        WORLD_WIDTH: 4200,
        WORLD_HEIGHT: 760,
        KILLZONE_Y: 720,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 560,
        CROWN_X: 3860,
        CROWN_Y: 400,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        NEXT_LEVEL: 12,
    },
    content: {
        instructions:
            'BASTION RELAY - Inside the enemy base. Wardens hold the line: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Red gates sweep the hall on a beat: cross on the dark. Drop through the grate trench mid-run. The gatehouse crushers guard the crown: stand center, cross between slams. New gun: TEMPEST, a 5-way fan. Press G to swap guns. Pods grant 30s of heavy fire. Free caged crew for −2s each. (M toggles music)',
        touchInstructions:
            'BASTION RELAY - Inside the base. The bolt button fires. New gun: TEMPEST. The gun button swaps guns. Cross the gates on the dark. Pods grant 30s guns. Free cages for −2s.',
        background: {
            type: 'bastion',
            style: 'relay',
            starCount: 0,
            color: 0x060a14,
            palette: {
                top: 0x060a14,
                mid: 0x12233d,
                bottom: 0x274b73,
                panel: 0x0d1626,
                seam: 0x16263f,
                girder: 0x1c2f4d,
                alert: 0xff4a3c,
                conduit: 0x9cecff,
                ground: 0x080d18,
            },
        },
        staticPlatforms: [
            { x: 420, y: 616, key: 'bastionDeck', scaleX: 6.4 },
            { x: 1240, y: 586, key: 'bastionDeck', scaleX: 6.4 },
            { x: 2060, y: 616, key: 'bastionDeck', scaleX: 6.4 },
            { x: 2813, y: 586, key: 'bastionDeck', scaleX: 5.0 },
            { x: 3451, y: 616, key: 'bastionDeck', scaleX: 4.0 },
            { x: 1400, y: 452, key: 'bastionGrate', scaleX: 5.0 },
            { x: 2950, y: 452, key: 'bastionGrate', scaleX: 4.4 },
            { x: 1650, y: 660, key: 'bastionGrate', scaleX: 2.4 },
            { x: 3840, y: 470, key: 'bastionDeck', scaleX: 3.6 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        props: [
            { x: 200, y: 580, key: 'bastionPylon' },
            { x: 1000, y: 550, key: 'bastionPylon' },
            { x: 2300, y: 580, key: 'bastionPylon' },
            { x: 3700, y: 434, key: 'bastionPylon' },
        ],
        checkpoints: [
            { x: 1800, y: 588 },
            { x: 3451, y: 588 },
        ],
        rescues: [{ x: 2950, y: 416 }],
        pods: [{ x: 2300, y: 504, gun: 'hail' }],
        dynamic: [
            { type: 'boarder', key: 'spireWarden', x: 700, y: 540, wave: 1 },
            { type: 'boarder', key: 'spireWarden', x: 1120, y: 540, wave: 1 },
            { type: 'boarder', key: 'spireWarden', x: 1800, y: 540, wave: 2 },
            { type: 'boarder', key: 'spireWarden', x: 2100, y: 540, wave: 2 },
            {
                type: 'laser',
                x: 1960,
                y: 540,
                length: 90,
                width: 16,
                orientation: 'vertical',
                tint: 0xff5a4a,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 160,
            },
            {
                type: 'laser',
                x: 2160,
                y: 540,
                length: 90,
                width: 16,
                orientation: 'vertical',
                tint: 0xff5a4a,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 1140,
            },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 1400,
                y: 360,
                patrol: { x: 1500, duration: 1600 },
            },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 2500,
                y: 480,
                patrol: { x: 2620, duration: 1600 },
            },
            {
                type: 'roller',
                x: 2900,
                y: 570,
                patrol: { x: 3020, duration: 1400 },
                spinDuration: 640,
            },
            { type: 'boarder', key: 'spireWarden', x: 3300, y: 540, wave: 3 },
            { type: 'boarder', key: 'spireWarden', x: 3550, y: 540, wave: 3 },
            {
                type: 'crusher',
                x: 3720,
                y: 330,
                slamY: 450,
                duration: 780,
                delay: 0,
                hold: 280,
            },
            {
                type: 'crusher',
                x: 3960,
                y: 330,
                slamY: 450,
                duration: 780,
                delay: 390,
                hold: 280,
            },
        ],
    },
};
