export const level = {
    id: 8,
    definition: {
        TITLE: 'Colony Drop',
        GRAVITY: 300,
        WORLD_WIDTH: 4200,
        WORLD_HEIGHT: 760,
        KILLZONE_Y: 720,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 560,
        CROWN_X: 3900,
        CROWN_Y: 400,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        CROWN_SHIELD: true,
        NEXT_LEVEL: 9,
    },
    content: {
        instructions:
            'COLONY DROP - Beachhead landing. Skitterers rush the line in waves: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Spore-mines drift; jump them or shoot past. The crown is shielded: drop every skitterer to open it. Press G to swap guns. (M toggles music)',
        touchInstructions:
            'COLONY DROP - Aliens rush the line. The bolt button fires the space phaser. The gun button swaps guns. Clear all skitterers to open the crown. Arrows move, jump leaps.',
        background: {
            type: 'colony',
            style: 'beachhead',
            starCount: 90,
            color: 0x0b0e22,
            palette: {
                top: 0x0b0e22,
                mid: 0x3a2a5e,
                bottom: 0xff8a4a,
                silhouette: 0x1c1740,
                tower: 0x2a2352,
                signal: 0xff5a4a,
                strip: 0xffb15a,
                ground: 0x0d0b1e,
            },
        },
        staticPlatforms: [
            { x: 420, y: 616, key: 'colonyDeck', scaleX: 6.4 },
            { x: 1240, y: 616, key: 'colonyDeck', scaleX: 6.4 },
            { x: 2060, y: 616, key: 'colonyDeck', scaleX: 6.4 },
            { x: 2813, y: 616, key: 'colonyDeck', scaleX: 5.0 },
            { x: 3451, y: 616, key: 'colonyDeck', scaleX: 4.0 },
            { x: 3800, y: 470, key: 'colonyDeck', scaleX: 3.0 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        props: [
            { x: 200, y: 582, key: 'colonyBeacon' },
            { x: 3451, y: 582, key: 'colonyBeacon' },
        ],
        dynamic: [
            { type: 'boarder', key: 'skitterling', x: 700, y: 540, wave: 1 },
            { type: 'boarder', key: 'skitterling', x: 1120, y: 540, wave: 1 },
            { type: 'boarder', key: 'skitterling', x: 1700, y: 540, wave: 2 },
            { type: 'boarder', key: 'skitterling', x: 2100, y: 540, wave: 2 },
            {
                type: 'drone',
                key: 'sporeFloater',
                x: 2500,
                y: 480,
                patrol: { x: 2620, duration: 1600 },
            },
            {
                type: 'roller',
                x: 2900,
                y: 570,
                patrol: { x: 3020, duration: 1400 },
                spinDuration: 640,
            },
            { type: 'boarder', key: 'skitterling', x: 3200, y: 540, wave: 3 },
            { type: 'boarder', key: 'skitterling', x: 3550, y: 540, wave: 3 },
        ],
    },
};
