export const level = {
    id: 12,
    definition: {
        TITLE: 'Crimson Womb',
        GRAVITY: 300,
        WORLD_WIDTH: 4400,
        WORLD_HEIGHT: 780,
        KILLZONE_Y: 740,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 580,
        CROWN_X: 4050,
        CROWN_Y: 236,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        CROWN_SHIELD: true,
        NEXT_LEVEL: 13,
        BRANCH: [13, 16],
    },
    content: {
        instructions:
            'CRIMSON WOMB - The heart of the enemy. Gnawers swarm in waves: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Drips fall in the low run, devils patrol the flesh. Cross the marrow bridge to the crown deck. A spore-beam guards the last gap: cross on the dark. The crown is shielded: drop every gnawer to open it. New gun: HAIL, a fan that punches through. Press G to swap guns. Pods grant 30s of heavy fire. (M toggles music)',
        branchInstructions:
            'Shoot the wounded core. Finish this level to choose: RUST HARBOR or the IRON VAULT branch. The vault rejoins the foundry.',
        touchInstructions:
            'CRIMSON WOMB - The alien heart. The bolt button fires. New gun: HAIL. The gun button swaps guns. Clear all gnawers to open the crown. Cross the beam on the dark. Pods grant 30s guns.',
        background: {
            type: 'womb',
            style: 'lair',
            starCount: 0,
            color: 0x12060c,
            palette: {
                top: 0x12060c,
                mid: 0x3d0f22,
                bottom: 0x6e1a2e,
                fold: 0x2a0a18,
                flesh: 0x4a1420,
                vein: 0xff5a8a,
                core: 0x67ffd2,
                ground: 0x160309,
            },
        },
        staticPlatforms: [
            { x: 400, y: 656, key: 'wombFlesh', scaleX: 6.0 },
            { x: 1150, y: 626, key: 'wombFlesh', scaleX: 5.0 },
            { x: 1850, y: 596, key: 'wombFlesh', scaleX: 5.0 },
            { x: 2550, y: 566, key: 'wombFlesh', scaleX: 5.0 },
            { x: 3050, y: 476, key: 'wombFlesh', scaleX: 4.0 },
            { x: 3600, y: 386, key: 'wombFlesh', scaleX: 3.4 },
            { x: 1250, y: 486, key: 'wombBone', scaleX: 4.6 },
            { x: 2550, y: 420, key: 'wombBone', scaleX: 4.0 },
            { x: 3830, y: 340, key: 'wombBone', scaleX: 1.4 },
            { x: 4050, y: 296, key: 'wombFlesh', scaleX: 3.0 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        props: [
            { x: 1150, y: 596, key: 'wombEye' },
            { x: 2400, y: 536, key: 'wombEye' },
            { x: 3600, y: 356, key: 'wombEye' },
        ],
        checkpoints: [
            { x: 1850, y: 568 },
            { x: 2950, y: 448 },
        ],
        rescues: [],
        pods: [{ x: 2000, y: 484, gun: 'ripper' }],
        dynamic: [
            { type: 'boarder', key: 'gnawer', x: 550, y: 600, wave: 1 },
            { type: 'drip', x: 600, y: 510, interval: 1600, delay: 0 },
            { type: 'drip', x: 750, y: 510, interval: 1600, delay: 750 },
            { type: 'boarder', key: 'gnawer', x: 1350, y: 570, wave: 2 },
            { type: 'boarder', key: 'gnawer', x: 2000, y: 540, wave: 2 },
            {
                type: 'dustDevil',
                x: 2550,
                y: 490,
                patrol: { x: 2630, duration: 1500 },
            },
            { type: 'boarder', key: 'gnawer', x: 2600, y: 510, wave: 3 },
            { type: 'boarder', key: 'gnawer', x: 3100, y: 420, wave: 3 },
            {
                type: 'drone',
                key: 'sporeFloater',
                x: 1250,
                y: 390,
                patrol: { x: 1350, duration: 1700 },
            },
            {
                type: 'drone',
                key: 'sporeFloater',
                x: 3100,
                y: 380,
                patrol: { x: 3200, duration: 1600 },
            },
            { type: 'boarder', key: 'gnawer', x: 3650, y: 330, wave: 4 },
            {
                type: 'laser',
                x: 3830,
                y: 245,
                length: 140,
                width: 14,
                orientation: 'vertical',
                tint: 0xff5a8a,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 500,
            },
        ],
    },
};
