export const level = {
    id: 7,
    definition: {
        TITLE: 'Earthwatch',
        GRAVITY: 280,
        WORLD_WIDTH: 3960,
        WORLD_HEIGHT: 760,
        KILLZONE_Y: 720,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 560,
        CROWN_X: 3640,
        CROWN_Y: 400,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        NEXT_LEVEL: 8,
    },
    content: {
        instructions:
            'EARTHWATCH - On the station hull, with Earth below. Aliens arrive in waves and run at you. Face them and press F or J to fire the space phaser. Gamepad uses the left face button. (M toggles music)',
        touchInstructions:
            'EARTHWATCH - On the station. Aliens arrive in waves. The bolt button fires the space phaser. Arrows move, jump leaps.',
        background: {
            type: 'iss',
            style: 'earthwatch',
            starCount: 90,
            color: 0x071018,
            palette: {
                top: 0x02040c,
                mid: 0x0a1c33,
                ocean: 0x1a6cae,
                land: 0x3f9a45,
                landDeep: 0x1f6a32,
                cloud: 0xf4fbff,
                atmosphere: 0x9ad7ff,
                hull: 0xc5d0dc,
                array: 0x1d4e89,
            },
        },
        staticPlatforms: [
            { x: 520, y: 616, key: 'issHull', scaleX: 8.2 },
            { x: 1540, y: 616, key: 'issHull', scaleX: 8.2 },
            { x: 2287, y: 616, key: 'issHull', scaleX: 3.95 },
            { x: 2872, y: 616, key: 'issHull', scaleX: 3.31 },
            { x: 3480, y: 616, key: 'issHull', scaleX: 6.4 },
            { x: 3520, y: 470, key: 'issHull', scaleX: 4.5 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        checkpoints: [
            { x: 2150, y: 570 },
            { x: 3120, y: 570 },
        ],
        dynamic: [
            { type: 'boarder', x: 700, y: 540, wave: 1 },
            { type: 'boarder', x: 1120, y: 540, wave: 1 },
            { type: 'boarder', x: 1560, y: 540, wave: 2 },
            { type: 'boarder', x: 2040, y: 540, wave: 2 },
            { type: 'boarder', x: 2480, y: 540, wave: 3 },
            { type: 'boarder', x: 2920, y: 540, wave: 3 },
            { type: 'boarder', x: 3320, y: 540, wave: 4 },
            { type: 'boarder', x: 3600, y: 400, wave: 4 },
        ],
    },
};
