export const level = {
    id: 14,
    definition: {
        TITLE: 'Ember Foundry',
        GRAVITY: 300,
        WORLD_WIDTH: 4600,
        WORLD_HEIGHT: 780,
        KILLZONE_Y: 740,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 580,
        CROWN_X: 4200,
        CROWN_Y: 254,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        NEXT_LEVEL: 15,
    },
    content: {
        instructions:
            'EMBER FOUNDRY - The smelter. Gnawers swarm in waves: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Ride the ore trams across the wide gaps, scale the chain vent tower, and cross the ember beams on the dark: warning means leave, active means do not cross. New gun: COMET, a tight five-way fan that punches through one. Press G to swap guns. Pods grant 30s of heavy fire. Free caged crew for −2s each. (M toggles music)',
        touchInstructions:
            'EMBER FOUNDRY - The smelter. The bolt button fires. New gun: COMET. The gun button swaps guns. Ride the trams. Cross the beams on the dark. Pods grant 30s guns. Free cages for −2s.',
        background: {
            type: 'foundry',
            style: 'smelter',
            starCount: 0,
            color: 0x140d0a,
            palette: {
                top: 0x140d0a,
                mid: 0x2a1410,
                bottom: 0x4a1e12,
                ember: 0xff6a2a,
                molten: 0xffd23c,
                wall: 0x241512,
                rail: 0x3a2c26,
                signal: 0x7dff9a,
            },
        },
        staticPlatforms: [
            { x: 400, y: 656, key: 'foundryDeck', scaleX: 6.0 },
            { x: 1150, y: 626, key: 'foundryDeck', scaleX: 5.0 },
            { x: 1850, y: 596, key: 'foundryDeck', scaleX: 5.0 },
            { x: 2550, y: 566, key: 'foundryDeck', scaleX: 5.0 },
            { x: 3150, y: 496, key: 'foundryDeck', scaleX: 4.0 },
            { x: 3700, y: 416, key: 'foundryDeck', scaleX: 3.4 },
            { x: 1300, y: 486, key: 'foundryChain', scaleX: 4.6 },
            { x: 2550, y: 414, key: 'foundryChain', scaleX: 4.0 },
            { x: 3850, y: 316, key: 'foundryChain', scaleX: 3.0 },
            { x: 3300, y: 440, key: 'foundryChain', scaleX: 1.4 },
            { x: 3300, y: 380, key: 'foundryChain', scaleX: 1.4 },
            { x: 4200, y: 326, key: 'foundryDeck', scaleX: 3.0 },
        ],
        floor: null,
        moving: [
            {
                x: 2200,
                y: 560,
                key: 'liftPlatform',
                scaleX: 1.15,
                tween: { y: 520, duration: 2000, delay: 0 },
            },
            {
                x: 3440,
                y: 450,
                key: 'liftPlatform',
                scaleX: 1.15,
                tween: { y: 410, duration: 2000, delay: 1000 },
            },
        ],
        rocks: [],
        props: [
            { x: 300, y: 624, key: 'foundryVent' },
            { x: 2000, y: 564, key: 'foundryVent' },
            { x: 2700, y: 538, key: 'foundryVent' },
            { x: 3050, y: 464, key: 'foundryVent' },
            { x: 3700, y: 384, key: 'foundryVent' },
        ],
        checkpoints: [
            { x: 1900, y: 556 },
            { x: 2950, y: 456 },
        ],
        rescues: [{ x: 3300, y: 344 }],
        pods: [{ x: 2050, y: 484, gun: 'halo' }],
        dynamic: [
            { type: 'boarder', key: 'gnawer', x: 550, y: 588, wave: 1 },
            { type: 'drip', x: 600, y: 500, interval: 1600, delay: 0 },
            { type: 'drip', x: 750, y: 500, interval: 1600, delay: 750 },
            { type: 'boarder', key: 'gnawer', x: 1100, y: 558, wave: 1 },
            { type: 'boarder', key: 'gnawer', x: 1700, y: 528, wave: 2 },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 1900,
                y: 476,
                patrol: { x: 2000, duration: 1600 },
            },
            { type: 'boarder', key: 'gnawer', x: 2450, y: 498, wave: 2 },
            {
                type: 'dustDevil',
                x: 2550,
                y: 478,
                patrol: { x: 2630, duration: 1500 },
            },
            { type: 'boarder', key: 'gnawer', x: 2600, y: 346, wave: 3 },
            { type: 'boarder', key: 'gnawer', x: 3100, y: 428, wave: 3 },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 3050,
                y: 400,
                patrol: { x: 3150, duration: 1800 },
            },
            { type: 'boarder', key: 'gnawer', x: 3650, y: 346, wave: 4 },
            {
                type: 'laser',
                x: 1560,
                y: 500,
                length: 110,
                width: 14,
                orientation: 'vertical',
                tint: 0xff6a2a,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 500,
            },
            {
                type: 'laser',
                x: 4010,
                y: 250,
                length: 130,
                width: 14,
                orientation: 'vertical',
                tint: 0xff6a2a,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 1100,
            },
            { type: 'boarder', key: 'gnawer', x: 4150, y: 258, wave: 4 },
        ],
    },
};
