export const level = {
    id: 9,
    definition: {
        TITLE: 'Hive Warrens',
        GRAVITY: 320,
        WORLD_WIDTH: 3800,
        WORLD_HEIGHT: 860,
        KILLZONE_Y: 820,
        PLAYER_START_X: 100,
        PLAYER_START_Y: 700,
        CROWN_X: 3600,
        CROWN_Y: 190,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        NEXT_LEVEL: 10,
    },
    content: {
        instructions:
            'HIVE WARRENS - The nest. Stomp the gold-capped beetle to launch up to the catwalk. Jaw doors slam on a beat: cross between slams. Acid drips fall in the low tunnel. Climb the fang shaft to the crown deck. Waves still answer to the space phaser: F or J. A spore-beam guards the crown deck: cross on the dark. Press G to swap guns. Pods grant 30s of heavy fire. (M toggles music)',
        touchInstructions:
            'HIVE WARRENS - Stomp the beetle to launch up. Time the jaw doors. The bolt button fires. The gun button swaps guns. Pods grant 30s guns.',
        background: {
            type: 'hive',
            style: 'warrens',
            starCount: 0,
            color: 0x0a1412,
            palette: {
                top: 0x0a1412,
                mid: 0x1c4d46,
                bottom: 0x3d1c4e,
                flesh: 0x24122e,
                chitin: 0x5e2a6e,
                chitinDark: 0x2c1238,
                glow: 0x67ffd2,
                spore: 0xc78bff,
            },
        },
        staticPlatforms: [
            { x: 250, y: 742, key: 'hiveChitin', scaleX: 4.8 },
            { x: 800, y: 580, key: 'hiveChitin', scaleX: 3.6 },
            { x: 1250, y: 560, key: 'hiveChitin', scaleX: 3.0 },
            { x: 1750, y: 700, key: 'hiveChitin', scaleX: 4.0 },
            { x: 2250, y: 620, key: 'hiveChitin', scaleX: 3.0 },
            { x: 2650, y: 540, key: 'hiveChitin', scaleX: 3.0 },
            { x: 3100, y: 420, key: 'hiveChitin', scaleX: 4.4 },
            { x: 250, y: 610, key: 'hiveFang', scaleX: 2.6 },
            { x: 2450, y: 480, key: 'hiveFang', scaleX: 3.0 },
            { x: 3350, y: 340, key: 'hiveFang', scaleX: 1.4 },
            { x: 3600, y: 260, key: 'hiveChitin', scaleX: 2.8 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        props: [
            { x: 800, y: 544, key: 'hiveSac' },
            { x: 1750, y: 664, key: 'hiveSac' },
            { x: 2650, y: 504, key: 'hiveSac' },
        ],
        checkpoints: [
            { x: 1600, y: 672 },
            { x: 2550, y: 512 },
        ],
        rescues: [],
        pods: [{ x: 1900, y: 588, gun: 'nova' }],
        dynamic: [
            {
                type: 'bonk',
                enemy: 'brute',
                key: 'hiveBrute',
                x: 380,
                y: 712,
                patrol: { x: 460, duration: 1700 },
                bodyWidth: 46,
                bodyHeight: 36,
            },
            {
                type: 'crusher',
                x: 1200,
                y: 400,
                slamY: 520,
                duration: 780,
                delay: 0,
                hold: 280,
            },
            {
                type: 'crusher',
                x: 1320,
                y: 400,
                slamY: 520,
                duration: 780,
                delay: 390,
                hold: 280,
            },
            { type: 'drip', x: 1700, y: 560, interval: 1600, delay: 0 },
            { type: 'drip', x: 1820, y: 560, interval: 1600, delay: 750 },
            {
                type: 'bonk',
                enemy: 'sentry',
                key: 'sentryOrb',
                x: 2900,
                y: 480,
                bobAmplitude: 18,
                bobDuration: 900,
                bodyWidth: 30,
                bodyHeight: 44,
            },
            { type: 'boarder', key: 'gnawer', x: 1100, y: 480, wave: 1 },
            { type: 'boarder', key: 'gnawer', x: 2250, y: 580, wave: 2 },
            { type: 'boarder', key: 'gnawer', x: 2350, y: 580, wave: 2 },
            { type: 'boarder', key: 'gnawer', x: 2700, y: 500, wave: 3 },
            { type: 'boarder', key: 'gnawer', x: 3150, y: 380, wave: 3 },
            { type: 'boarder', key: 'gnawer', x: 3500, y: 220, wave: 4 },
            {
                type: 'laser',
                x: 3550,
                y: 180,
                length: 120,
                width: 14,
                orientation: 'vertical',
                tint: 0x67ffd2,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 500,
            },
        ],
    },
};
