export const level = {
    id: 16,
    definition: {
        TITLE: 'Iron Vault',
        GRAVITY: 300,
        WORLD_WIDTH: 3200,
        WORLD_HEIGHT: 760,
        KILLZONE_Y: 720,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 580,
        CROWN_X: 2750,
        CROWN_Y: 374,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        CROWN_SHIELD: true,
        NEXT_LEVEL: 14,
    },
    content: {
        instructions:
            'IRON VAULT - The sealed branch. You chose the vault path: it rejoins the foundry. Skitterlings swarm in waves: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Cross the beam on the dark and slip the pad slam. The crown is shielded: drop every skitterling to open it. Gun pods grant 30s of heavy fire. Free caged crew for −2s each. Press G to swap guns. (M toggles music)',
        touchInstructions:
            'IRON VAULT - The sealed branch. The bolt button fires. The gun button swaps guns. Clear all skitterlings to open the crown. Cross the beam on the dark, slip the slam. Pods grant 30s guns. Free cages for −2s.',
        background: {
            type: 'bastion',
            style: 'vault',
            starCount: 0,
            color: 0x0d1119,
            palette: {
                top: 0x0d1119,
                mid: 0x1c2230,
                bottom: 0x39435a,
                panel: 0x2c3a52,
                seam: 0x9cecff,
                door: 0x8a99b5,
                pipe: 0x141c30,
                lamp: 0xffb15a,
            },
        },
        staticPlatforms: [
            { x: 380, y: 636, key: 'vaultDeck', scaleX: 5.0 },
            { x: 1050, y: 606, key: 'vaultDeck', scaleX: 4.0 },
            { x: 1650, y: 576, key: 'vaultDeck', scaleX: 4.0 },
            { x: 2250, y: 516, key: 'vaultDeck', scaleX: 3.4 },
            { x: 1100, y: 470, key: 'bastionGrate', scaleX: 3.0 },
            { x: 2200, y: 380, key: 'bastionGrate', scaleX: 2.6 },
            { x: 2750, y: 446, key: 'vaultDeck', scaleX: 3.0 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        props: [
            { x: 500, y: 600, key: 'vaultSeal' },
            { x: 1700, y: 540, key: 'vaultSeal' },
        ],
        checkpoints: [
            { x: 1100, y: 566 },
            { x: 2250, y: 476 },
        ],
        rescues: [{ x: 1100, y: 434 }],
        pods: [{ x: 1500, y: 480, gun: 'comet' }],
        dynamic: [
            { type: 'boarder', key: 'skitterling', x: 400, y: 568, wave: 1 },
            { type: 'boarder', key: 'skitterling', x: 900, y: 538, wave: 1 },
            { type: 'boarder', key: 'skitterling', x: 1600, y: 508, wave: 2 },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 1700,
                y: 470,
                patrol: { x: 1800, duration: 1600 },
            },
            { type: 'boarder', key: 'skitterling', x: 2150, y: 448, wave: 2 },
            { type: 'boarder', key: 'skitterling', x: 2300, y: 312, wave: 3 },
            {
                type: 'laser',
                x: 2450,
                y: 440,
                length: 90,
                width: 14,
                orientation: 'vertical',
                tint: 0xff4a3c,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 600,
            },
            {
                type: 'crusher',
                x: 2830,
                y: 320,
                slamY: 416,
                duration: 780,
                delay: 0,
            },
            { type: 'boarder', key: 'skitterling', x: 2700, y: 378, wave: 3 },
        ],
    },
};
