export const level = {
    id: 6,
    definition: {
        TITLE: 'Red Reach',
        GRAVITY: 220,
        WORLD_WIDTH: 3080,
        WORLD_HEIGHT: 780,
        KILLZONE_Y: 740,
        PLAYER_START_X: 90,
        PLAYER_START_Y: 560,
        CROWN_X: 3000,
        CROWN_Y: 200,
        BOMB_SPEED: 190,
        KILLZONE_HEIGHT: 36,
        NEXT_LEVEL: 7,
    },
    content: {
        instructions:
            'RED REACH - Gold shells are springs. Stomp the marked beetle to cross the canyon. Dust, boulders, and steam are not. (M toggles music)',
        touchInstructions: 'RED REACH - Stomp a gold shell to bounce. Arrows move, jump leaps.',
        background: {
            type: 'mars',
            style: 'redReach',
            starCount: 80,
            color: 0x3a120c,
            palette: {
                top: 0x2a0c14,
                mid: 0xc45a3a,
                bottom: 0xf0b56a,
                surface: 0xc4623a,
                dune: 0x9a3d28,
                highlight: 0xffd0a4,
                shadow: 0x4a1c16,
                dust: 0xffb15a,
            },
        },
        staticPlatforms: [
            { x: 200, y: 620, key: 'mesa', scaleX: 3.6, scaleY: 1 },
            { x: 1334, y: 648, key: 'mesa', scaleX: 2.8, scaleY: 1 },
            { x: 1700, y: 560, key: 'mesa', scaleX: 2.2, scaleY: 1 },
            { x: 2060, y: 470, key: 'mesa', scaleX: 2.2, scaleY: 1 },
            { x: 2400, y: 380, key: 'mesa', scaleX: 2.0, scaleY: 1 },
            { x: 2720, y: 300, key: 'mesa', scaleX: 2.0, scaleY: 1 },
            { x: 3000, y: 220, key: 'mesa', scaleX: 1.4, scaleY: 1 },
        ],
        floor: null,
        moving: [],
        rocks: [{ x: 1450, y: 620, key: 'marsSpike' }],
        props: [{ x: 120, y: 586, key: 'bonkSign' }],
        dynamic: [
            {
                type: 'bonk',
                enemy: 'beetle',
                key: 'beetle',
                x: 480,
                y: 657,
                patrol: { x: 540, duration: 1800 },
                bodyWidth: 44,
                bodyHeight: 34,
            },
            {
                type: 'dustDevil',
                x: 1560,
                y: 560,
                patrol: { x: 1640, duration: 1500 },
            },
            {
                type: 'bonk',
                enemy: 'beetle',
                key: 'beetle',
                x: 1660,
                y: 527,
                patrol: { x: 1760, duration: 1500, delay: 180 },
                bodyWidth: 44,
                bodyHeight: 34,
            },
            {
                type: 'roller',
                x: 2000,
                y: 434,
                patrol: { x: 2120, duration: 1400 },
                spinDuration: 640,
            },
            {
                type: 'laser',
                x: 2400,
                y: 310,
                length: 80,
                width: 16,
                orientation: 'vertical',
                tint: 0xffb15a,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 160,
            },
            {
                type: 'bonk',
                enemy: 'hopper',
                key: 'hopper',
                x: 2860,
                y: 400,
                bobAmplitude: 18,
                bobDuration: 700,
                bodyWidth: 24,
                bodyHeight: 52,
            },
        ],
    },
};
