export const level = {
    id: 13,
    definition: {
        TITLE: 'Rust Harbor',
        GRAVITY: 300,
        WORLD_WIDTH: 4600,
        WORLD_HEIGHT: 780,
        KILLZONE_Y: 740,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 580,
        CROWN_X: 4250,
        CROWN_Y: 258,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        CROWN_SHIELD: true,
        NEXT_LEVEL: 14,
    },
    content: {
        instructions:
            'RUST HARBOR - The breaker yard. Skitterlings swarm in waves: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Drips fall on the low run, a sentry bobs over the high shelf. Climb the plank stair past the high decks. Cargo slams guard the crown deck: cross between slams. The crown is shielded: drop every skitterling to open it. New gun: RIPPER, a wide fan that punches through one. Press G to swap guns. Pods grant 30s of heavy fire. Free caged crew for −2s each. (M toggles music)',
        touchInstructions:
            'RUST HARBOR - The breaker yard. The bolt button fires. New gun: RIPPER. The gun button swaps guns. Clear all skitterlings to open the crown. Cross the slams between drops. Pods grant 30s guns. Free cages for −2s.',
        background: {
            type: 'harbor',
            style: 'dusk',
            starCount: 0,
            color: 0x1b2b4a,
            palette: {
                top: 0x1b2b4a,
                mid: 0x4a3a52,
                bottom: 0xff9a4a,
                sun: 0xffd7a8,
                hull: 0x141c30,
                porthole: 0xff9a4a,
                crane: 0x2c3a52,
                box: 0x6e3a22,
                piling: 0x0a101c,
                shimmer: 0xff9a4a,
                water: 0x0a1626,
            },
        },
        staticPlatforms: [
            { x: 400, y: 656, key: 'harborDeck', scaleX: 6.0 },
            { x: 1150, y: 630, key: 'harborDeck', scaleX: 5.0 },
            { x: 1850, y: 600, key: 'harborDeck', scaleX: 5.0 },
            { x: 2550, y: 570, key: 'harborDeck', scaleX: 5.0 },
            { x: 3200, y: 500, key: 'harborDeck', scaleX: 4.0 },
            { x: 3750, y: 420, key: 'harborDeck', scaleX: 3.4 },
            { x: 1250, y: 490, key: 'harborPlank', scaleX: 4.6 },
            { x: 2600, y: 424, key: 'harborPlank', scaleX: 4.0 },
            { x: 3900, y: 320, key: 'harborPlank', scaleX: 3.0 },
            { x: 3450, y: 470, key: 'harborPlank', scaleX: 1.6 },
            { x: 4250, y: 330, key: 'harborDeck', scaleX: 3.0 },
        ],
        floor: null,
        moving: [],
        rocks: [],
        props: [
            { x: 200, y: 620, key: 'harborLamp' },
            { x: 950, y: 594, key: 'harborLamp' },
            { x: 1300, y: 594, key: 'harborLamp' },
            { x: 2500, y: 534, key: 'harborLamp' },
            { x: 3650, y: 384, key: 'harborLamp' },
        ],
        checkpoints: [
            { x: 1900, y: 560 },
            { x: 3300, y: 460 },
        ],
        rescues: [{ x: 2700, y: 388 }],
        pods: [{ x: 2050, y: 488, gun: 'comet' }],
        dynamic: [
            { type: 'boarder', key: 'skitterling', x: 550, y: 588, wave: 1 },
            { type: 'drip', x: 600, y: 500, interval: 1600, delay: 0 },
            { type: 'drip', x: 750, y: 500, interval: 1600, delay: 750 },
            { type: 'boarder', key: 'skitterling', x: 1100, y: 562, wave: 1 },
            {
                type: 'bonk',
                enemy: 'sentry',
                key: 'sentryOrb',
                x: 1250,
                y: 430,
                bobAmplitude: 18,
                bobDuration: 900,
                bodyWidth: 30,
                bodyHeight: 30,
            },
            { type: 'boarder', key: 'skitterling', x: 1700, y: 532, wave: 2 },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 1900,
                y: 480,
                patrol: { x: 2000, duration: 1600 },
            },
            { type: 'boarder', key: 'skitterling', x: 2450, y: 502, wave: 2 },
            {
                type: 'dustDevil',
                x: 2550,
                y: 482,
                patrol: { x: 2630, duration: 1500 },
            },
            { type: 'boarder', key: 'skitterling', x: 2600, y: 356, wave: 3 },
            { type: 'boarder', key: 'skitterling', x: 3150, y: 432, wave: 3 },
            { type: 'boarder', key: 'skitterling', x: 3700, y: 350, wave: 4 },
            {
                type: 'crusher',
                x: 4180,
                y: 200,
                slamY: 300,
                duration: 780,
                delay: 0,
            },
            {
                type: 'crusher',
                x: 4320,
                y: 180,
                slamY: 300,
                duration: 780,
                delay: 390,
            },
            { type: 'boarder', key: 'skitterling', x: 4130, y: 262, wave: 4 },
        ],
    },
};
