export const level = {
    id: 15,
    definition: {
        TITLE: 'Skyhook Anchor',
        GRAVITY: 300,
        WORLD_WIDTH: 4600,
        WORLD_HEIGHT: 780,
        KILLZONE_Y: 740,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 580,
        CROWN_X: 4200,
        CROWN_Y: 254,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        CROWN_SHIELD: true,
        NEXT_LEVEL: null,
    },
    content: {
        instructions:
            'SKYHOOK ANCHOR - The tether station. Wardens swarm in waves: face them and press F or J to fire the space phaser. Gamepad uses the left face button. Take the panel stair, ride the anchor lift, cross the beam on the dark, and slip the slam on the crown pad. The crown is shielded: drop every warden to open it. New gun: HALO, a piercing orb that never stops. Press G to swap guns. Pods grant 30s of heavy fire. Free caged crew for −2s each. (M toggles music)',
        touchInstructions:
            'SKYHOOK ANCHOR - The tether station. The bolt button fires. New gun: HALO. The gun button swaps guns. Clear all wardens to open the crown. Ride the lift, cross on the dark, slip the slam. Pods grant 30s guns. Free cages for −2s.',
        background: {
            type: 'skyhook',
            style: 'night',
            starCount: 0,
            color: 0x060b18,
            palette: {
                top: 0x060b18,
                mid: 0x101a33,
                bottom: 0x1d2c4d,
                ribbon: 0x7df9ff,
                climber: 0xffb15a,
                tower: 0x1d2c4d,
                beacon: 0xff4a3c,
                pylon: 0x39435a,
                panel: 0x141c30,
                slab: 0x39435a,
                pipe: 0x0a0f1c,
            },
        },
        staticPlatforms: [
            { x: 400, y: 656, key: 'skyhookDeck', scaleX: 6.0 },
            { x: 1150, y: 626, key: 'skyhookDeck', scaleX: 5.0 },
            { x: 1850, y: 596, key: 'skyhookDeck', scaleX: 5.0 },
            { x: 2550, y: 566, key: 'skyhookDeck', scaleX: 5.0 },
            { x: 3150, y: 496, key: 'skyhookDeck', scaleX: 4.0 },
            { x: 3700, y: 416, key: 'skyhookDeck', scaleX: 3.4 },
            { x: 1300, y: 486, key: 'skyhookPanel', scaleX: 4.6 },
            { x: 2550, y: 414, key: 'skyhookPanel', scaleX: 4.0 },
            { x: 3850, y: 310, key: 'skyhookPanel', scaleX: 3.0 },
            { x: 3700, y: 356, key: 'skyhookPanel', scaleX: 1.6 },
            { x: 4200, y: 326, key: 'skyhookDeck', scaleX: 3.2 },
        ],
        floor: null,
        moving: [
            {
                x: 3950,
                y: 480,
                key: 'liftPlatform',
                scaleX: 1.15,
                tween: { y: 410, duration: 2400, delay: 0 },
            },
        ],
        rocks: [],
        props: [
            { x: 300, y: 624, key: 'tetherClamp' },
            { x: 1150, y: 594, key: 'tetherClamp' },
            { x: 2000, y: 564, key: 'tetherClamp' },
            { x: 3300, y: 464, key: 'tetherClamp' },
            { x: 4100, y: 294, key: 'tetherClamp' },
        ],
        checkpoints: [
            { x: 1900, y: 556 },
            { x: 3300, y: 456 },
        ],
        rescues: [{ x: 2450, y: 378 }],
        pods: [{ x: 2050, y: 484, gun: 'tempest' }],
        dynamic: [
            { type: 'boarder', key: 'spireWarden', x: 550, y: 588, wave: 1 },
            { type: 'drip', x: 600, y: 500, interval: 1600, delay: 0 },
            { type: 'drip', x: 750, y: 500, interval: 1600, delay: 750 },
            { type: 'boarder', key: 'spireWarden', x: 1100, y: 558, wave: 1 },
            { type: 'boarder', key: 'spireWarden', x: 1700, y: 528, wave: 2 },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 1900,
                y: 476,
                patrol: { x: 2000, duration: 1600 },
            },
            { type: 'boarder', key: 'spireWarden', x: 2450, y: 498, wave: 2 },
            {
                type: 'dustDevil',
                x: 2550,
                y: 478,
                patrol: { x: 2630, duration: 1500 },
            },
            { type: 'boarder', key: 'spireWarden', x: 2600, y: 346, wave: 3 },
            { type: 'boarder', key: 'spireWarden', x: 3100, y: 428, wave: 3 },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 3150,
                y: 400,
                patrol: { x: 3250, duration: 1800 },
            },
            { type: 'boarder', key: 'spireWarden', x: 3650, y: 346, wave: 4 },
            {
                type: 'laser',
                x: 4020,
                y: 300,
                length: 200,
                width: 14,
                orientation: 'vertical',
                tint: 0x7df9ff,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 1100,
            },
            {
                type: 'crusher',
                x: 4280,
                y: 180,
                slamY: 296,
                duration: 780,
                delay: 200,
            },
            { type: 'boarder', key: 'spireWarden', x: 4120, y: 258, wave: 4 },
        ],
    },
};
