export const level = {
    id: 5,
    definition: {
        TITLE: 'Specimen Wing',
        GRAVITY: 330,
        WORLD_WIDTH: 2720,
        WORLD_HEIGHT: 860,
        KILLZONE_Y: 820,
        PLAYER_START_X: 100,
        PLAYER_START_Y: 700,
        CROWN_X: 2580,
        CROWN_Y: 130,
        BOMB_SPEED: 210,
        KILLZONE_HEIGHT: 36,
        NEXT_LEVEL: 6,
    },
    content: {
        instructions:
            'SPECIMEN WING - Gold heads are springs. Drop on the marked one to reach the catwalk. A side touch still fails the run. (M toggles music)',
        touchInstructions:
            'SPECIMEN WING - Drop onto a gold head to bounce up. Arrows move, jump leaps.',
        background: {
            type: 'facility',
            style: 'specimenWing',
            color: 0x071016,
            palette: {
                top: 0x071016,
                mid: 0x12343c,
                bottom: 0x1c4d46,
                metal: 0x1a3038,
                metalAlt: 0x24545a,
                glow: 0x67ffd2,
                accent: 0xd6ff4a,
                glass: 0x8ee7ff,
                shadow: 0x060d12,
            },
        },
        staticPlatforms: [
            { x: 250, y: 742, key: 'labDeck', scaleX: 4.8, scaleY: 1 },
            { x: 390, y: 320, key: 'labDeck', scaleX: 2.6, scaleY: 1 },
            { x: 860, y: 370, key: 'labDeck', scaleX: 2.2, scaleY: 1 },
            { x: 1220, y: 330, key: 'labDeck', scaleX: 2.2, scaleY: 1 },
            { x: 1560, y: 410, key: 'labDeck', scaleX: 2.4, scaleY: 1 },
            { x: 1940, y: 360, key: 'labDeck', scaleX: 2.0, scaleY: 1 },
            { x: 2280, y: 280, key: 'labDeck', scaleX: 1.8, scaleY: 1 },
            { x: 2580, y: 200, key: 'labDeck', scaleX: 2.2, scaleY: 1 },
        ],
        floor: null,
        moving: [
            {
                x: 2140,
                y: 390,
                key: 'liftPlatform',
                scaleX: 1.15,
                scaleY: 0.42,
                tween: { y: 270, duration: 2200, delay: 280 },
            },
        ],
        rocks: [],
        props: [
            { x: 130, y: 712, key: 'bonkSign' },
            { x: 78, y: 708, key: 'specimenJar' },
            { x: 188, y: 708, key: 'specimenJar' },
        ],
        dynamic: [
            {
                type: 'bonk',
                enemy: 'lab_tech',
                key: 'labTech',
                x: 330,
                y: 702,
                patrol: { x: 430, duration: 2200 },
                bodyWidth: 30,
                bodyHeight: 56,
            },
            {
                type: 'bonk',
                enemy: 'sentry',
                key: 'sentryOrb',
                x: 640,
                y: 470,
                bobAmplitude: 18,
                bobDuration: 900,
                bodyWidth: 30,
                bodyHeight: 44,
            },
            {
                type: 'laser',
                x: 860,
                y: 300,
                length: 150,
                width: 12,
                orientation: 'vertical',
                tint: 0x44ffd0,
                onDuration: 820,
                offDuration: 1100,
                startDelay: 180,
            },
            { type: 'drip', x: 1160, y: 70, interval: 1600, delay: 0 },
            { type: 'drip', x: 1280, y: 70, interval: 1600, delay: 700 },
            { type: 'drip', x: 1900, y: 70, interval: 1500, delay: 400 },
            {
                type: 'bonk',
                enemy: 'lab_tech',
                key: 'labTech',
                x: 1500,
                y: 370,
                patrol: { x: 1620, duration: 1500, delay: 200 },
                bodyWidth: 30,
                bodyHeight: 56,
            },
            {
                type: 'bonk',
                enemy: 'specimen',
                key: 'specimen',
                x: 2420,
                y: 235,
                bobAmplitude: 22,
                bobDuration: 860,
                bodyWidth: 32,
                bodyHeight: 46,
            },
        ],
    },
};
