export const level = {
    id: 10,
    definition: {
        TITLE: 'Spire Crown',
        GRAVITY: 280,
        WORLD_WIDTH: 4400,
        WORLD_HEIGHT: 780,
        KILLZONE_Y: 740,
        PLAYER_START_X: 150,
        PLAYER_START_Y: 580,
        CROWN_X: 3950,
        CROWN_Y: 170,
        BOMB_SPEED: 200,
        KILLZONE_HEIGHT: 36,
        PHASER: true,
        NEXT_LEVEL: null,
    },
    content: {
        instructions:
            'SPIRE CROWN - The final ascent. Gold beams sweep the hall on a beat: cross on the dark. Plasma devils guard the plaza, wardens hold the crown steps. Ride the lift, take the crown. Face them and press F or J to fire. Press G to swap guns. (M toggles music)',
        touchInstructions:
            'SPIRE CROWN - Cross the beams on the dark. Ride the lift to the crown. The bolt button fires. The gun button swaps guns.',
        background: {
            type: 'spire',
            style: 'crown',
            starCount: 90,
            color: 0x060818,
            palette: {
                top: 0x060818,
                mid: 0x1a2a5e,
                bottom: 0x0a0d20,
                planet: 0x2d6bb0,
                ring: 0x9cecff,
                gold: 0x8a6a1c,
                bright: 0xffe14a,
                hull: 0x101828,
                seam: 0xf4f7fb,
            },
        },
        staticPlatforms: [
            { x: 300, y: 660, key: 'spireAlloy', scaleX: 5.0 },
            { x: 900, y: 600, key: 'spireAlloy', scaleX: 3.0 },
            { x: 1350, y: 540, key: 'spireAlloy', scaleX: 3.0 },
            { x: 1850, y: 540, key: 'spireAlloy', scaleX: 4.0 },
            { x: 2400, y: 480, key: 'spireAlloy', scaleX: 3.0 },
            { x: 2850, y: 420, key: 'spireAlloy', scaleX: 3.0 },
            { x: 3300, y: 360, key: 'spireAlloy', scaleX: 3.0 },
            { x: 3950, y: 240, key: 'spireAlloy', scaleX: 2.6 },
        ],
        floor: null,
        moving: [
            {
                x: 3650,
                y: 360,
                key: 'liftPlatform',
                scaleX: 1.15,
                scaleY: 0.42,
                tween: { y: 240, duration: 2200, delay: 280 },
            },
        ],
        rocks: [],
        props: [],
        dynamic: [
            {
                type: 'laser',
                x: 1750,
                y: 470,
                length: 90,
                width: 16,
                orientation: 'vertical',
                tint: 0xffd48c,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 160,
            },
            {
                type: 'laser',
                x: 1950,
                y: 470,
                length: 90,
                width: 16,
                orientation: 'vertical',
                tint: 0xffd48c,
                onDuration: 780,
                offDuration: 1180,
                startDelay: 1140,
            },
            {
                type: 'dustDevil',
                x: 2400,
                y: 400,
                patrol: { x: 2480, duration: 1500 },
            },
            {
                type: 'drone',
                key: 'voltOrb',
                x: 2850,
                y: 330,
                patrol: { x: 2950, duration: 1600 },
            },
            { type: 'boarder', key: 'spireWarden', x: 900, y: 560, wave: 1 },
            { type: 'boarder', key: 'spireWarden', x: 1900, y: 500, wave: 2 },
            { type: 'boarder', key: 'spireWarden', x: 2400, y: 440, wave: 2 },
            { type: 'boarder', key: 'spireWarden', x: 2900, y: 380, wave: 3 },
            { type: 'boarder', key: 'spireWarden', x: 3300, y: 320, wave: 3 },
            { type: 'boarder', key: 'spireWarden', x: 3800, y: 200, wave: 4 },
        ],
    },
};
